---
- name: install python with Mastodon and CouchDB
  hosts: COMP90024
  become: yes
  tasks:
    - name: install Python3, pip
      apt:
        name: ["python3", "python3-pip", "unzip"]
        state: latest
      
    - name: install Mastodon and CouchDB
      pip:
        name: "Mastodon.py, couchdb"
        state: latest
        
    - copy:
        src: ../src
        dest: ./

    - name: install and config couchdb
      shell: |
        sudo snap install couchdb
        sudo systemctl enable snap.couchdb.server.service
        sudo snap restart couchdb
        sudo rm -f /var/snap/couchdb/current/etc/local.ini
        sudo cp ./src/local.ini /var/snap/couchdb/current/etc/
        sudo snap restart couchdb

    
    - name: run mastodon harvester
      ansible.builtin.command:
        cmd: "python3 ./src/harvester.py"
